spring:
  cloud:
    gateway:
      routes:
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
          filters:
            - AuthenticationFilter

        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion/**
          filters:
            - AuthenticationFilter

        - id: currency-tax-calculation
          uri: lb://currency-tax-calculation
          predicates:
            - Path=/currency-tax-calculation/**
          filters:
            - AuthenticationFilter


        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
